In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [9]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                 test_size=0.2)

In [7]:
x_train

    age  gender  fever   cough       city
79   48  Female  103.0    Mild    Kolkata
54   60  Female   99.0    Mild     Mumbai
56   71    Male    NaN  Strong    Kolkata
7    20  Female    NaN  Strong     Mumbai
18   64  Female   98.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
16   69  Female  103.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
21   73    Male   98.0    Mild  Bangalore
25   23    Male    NaN    Mild     Mumbai
49   44    Male  104.0    Mild     Mumbai

[80 rows x 5 columns]

Using Encoding

In [8]:
si=SimpleImputer()
x_train_fever =si.fit_transform(x_train[['fever']])
x_test_fever =si.fit_transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [12]:
oe =OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [15]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first')
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [16]:
# Extracting Age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape

(80, 1)

In [19]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
# also the test data
x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

x_train_transformed.shape

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 2 has 0 dimension(s)

In [20]:
from sklearn.compose import ColumnTransformer

In [24]:
transformer = ColumnTransformer(transformers=[
    ('t1',SimpleImputer(),['fever']),
    ('t2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('t3',OneHotEncoder(drop='first'),['gende','city'])
],remainder='passthrough')

In [34]:
transformer.fit_transform(x_train).shape

ValueError: A given column is not a column of the dataframe

In [35]:
transformer.transform(x_test).shape

AttributeError: 'ColumnTransformer' object has no attribute 'transformers_'